---
ID: "d78f2bd6-6d1c-4e95-9883-e1ea2ab6ee2d"
Parent: "abf0b70c-9404-4e39-b5c8-148e9db534ec"
Template: "a7dc8f8e-f004-46c8-9e31-b2ba852e3df3"
Path: "/sitecore/system/Settings/Foundation/ApiGenerators/Configurations/output-types/application json"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: application/json
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171201T230321Z
    - ID: "2c9e1974-f4a6-4dd1-9e7a-d3efa85ae339"
      Hint: Key
      Value: application/json
    - ID: "dd48a3bd-d48d-4109-8519-037a30a52257"
      Hint: Value
      Value: "{D78F2BD6-6D1C-4E95-9883-E1EA2AB6EE2D}"
